# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-03 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20180203_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='mywalletmodal',
            name='user_contact_no1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mywalletmodal',
            name='user_contact_no2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mywalletmodal',
            name='user_location',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='mywalletmodal',
            name='user_zip_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
