# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-03 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20180203_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywalletmodal',
            name='product_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
