# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-06 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_messagemodal'),
    ]

    operations = [
        migrations.AddField(
            model_name='mywalletmodal',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='mywalletmodal',
            name='total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
