# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-06 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=25)),
                ('category_discrption', models.TextField()),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=25)),
                ('product_code', models.IntegerField()),
                ('product_description', models.TextField()),
                ('price', models.IntegerField()),
                ('tax', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('pdt_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=25)),
                ('sub_category_title', models.CharField(max_length=25)),
                ('sub_category_disc', models.TextField()),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='productmodel',
            name='pdt_sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.SubCategory'),
        ),
    ]
