# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-06 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
        migrations.RenameModel(
            old_name='SubCategory',
            new_name='SubCategories',
        ),
    ]
