# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-06 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20180106_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Size')),
                ('stock_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductModel')),
            ],
        ),
    ]
