# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-27 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_productmodel_pdt_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='pdt_image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
